import { UserProfile, Vehicle, ServiceProvider, AssistanceRequest, SafePlace, EmergencyContact } from '../types';

export const INITIAL_CUSTOMERS: UserProfile[] = [
  {
    id: 'cust-1',
    name: 'Ramesh Kumar',
    email: 'ramesh.kumar@gmail.com',
    phone: '+91 98401 23456',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    selectedLanguage: 'en',
    theme: 'system',
    activeVehicleId: 'veh-1',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Priya Sundaram',
    email: 'priya.sundaram@outlook.com',
    phone: '+91 98412 87654',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    selectedLanguage: 'ta',
    theme: 'light',
    activeVehicleId: 'veh-2',
    createdAt: '2024-02-14T09:30:00Z',
  },
  {
    id: 'cust-3',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@yahoo.in',
    phone: '+91 99520 11223',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    selectedLanguage: 'hi',
    theme: 'dark',
    activeVehicleId: 'veh-3',
    createdAt: '2024-03-01T14:15:00Z',
  },
  {
    id: 'cust-4',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@gmail.com',
    phone: '+91 97890 44556',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    selectedLanguage: 'en',
    theme: 'system',
    activeVehicleId: 'veh-4',
    createdAt: '2024-03-15T18:40:00Z',
  },
  {
    id: 'cust-5',
    name: 'Karthik Venkat',
    email: 'karthik.v@techmail.com',
    phone: '+91 94440 66778',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    selectedLanguage: 'ta',
    theme: 'dark',
    activeVehicleId: 'veh-5',
    createdAt: '2024-04-02T11:20:00Z',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    userId: 'cust-1',
    type: 'car',
    make: 'Hyundai',
    model: 'Creta SX(O)',
    year: 2022,
    plateNumber: 'TN 07 BZ 4590',
    fuelType: 'diesel',
    isDefault: true,
  },
  {
    id: 'veh-2',
    userId: 'cust-1',
    type: 'bike',
    make: 'Royal Enfield',
    model: 'Classic 350',
    year: 2021,
    plateNumber: 'TN 09 CK 1289',
    fuelType: 'petrol',
    isDefault: false,
  },
  {
    id: 'veh-3',
    userId: 'cust-2',
    type: 'ev',
    make: 'Tata',
    model: 'Nexon EV Max',
    year: 2023,
    plateNumber: 'TN 38 DF 7721',
    fuelType: 'electric',
    isDefault: true,
  },
  {
    id: 'veh-4',
    userId: 'cust-2',
    type: 'bike',
    make: 'Honda',
    model: 'Activa 6G',
    year: 2022,
    plateNumber: 'TN 38 BE 3314',
    fuelType: 'petrol',
    isDefault: false,
  },
  {
    id: 'veh-5',
    userId: 'cust-3',
    type: 'car',
    make: 'Maruti Suzuki',
    model: 'Swift ZXi+',
    year: 2020,
    plateNumber: 'KA 03 MX 8812',
    fuelType: 'petrol',
    isDefault: true,
  },
  {
    id: 'veh-6',
    userId: 'cust-3',
    type: 'bike',
    make: 'Ather',
    model: '450X Gen 3',
    year: 2023,
    plateNumber: 'KA 05 EM 4901',
    fuelType: 'electric',
    isDefault: false,
  },
  {
    id: 'veh-7',
    userId: 'cust-4',
    type: 'car',
    make: 'Mahindra',
    model: 'Thar 4x4',
    year: 2022,
    plateNumber: 'TN 02 AS 9090',
    fuelType: 'diesel',
    isDefault: true,
  },
  {
    id: 'veh-8',
    userId: 'cust-4',
    type: 'bike',
    make: 'Yamaha',
    model: 'YZF R15 V4',
    year: 2023,
    plateNumber: 'TN 02 BN 6610',
    fuelType: 'petrol',
    isDefault: false,
  },
  {
    id: 'veh-9',
    userId: 'cust-5',
    type: 'car',
    make: 'Kia',
    model: 'Seltos GTX+',
    year: 2021,
    plateNumber: 'TN 58 AX 2341',
    fuelType: 'petrol',
    isDefault: true,
  },
  {
    id: 'veh-10',
    userId: 'cust-5',
    type: 'truck',
    make: 'Tata',
    model: 'Ace Gold Diesel',
    year: 2020,
    plateNumber: 'TN 58 BC 9012',
    fuelType: 'diesel',
    isDefault: false,
  },
];

// Centered around Chennai OMR Tech Corridor (12.9249, 80.2272)
export const INITIAL_PROVIDERS: ServiceProvider[] = [
  {
    id: 'prov-1',
    name: 'Murugan Selvam',
    businessName: 'Murugan QuickFix Mobile Auto Care',
    phone: '+91 98409 55112',
    email: 'murugan.quickfix@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 342,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['fuel', 'tyre', 'battery', 'breakdown', 'mechanical'],
    serviceArea: 'OMR, Sholinganallur, Thoraipakkam, Perungudi',
    currentLocation: {
      lat: 12.9352,
      lng: 80.2315,
      address: 'Near Sholinganallur Signal, OMR, Chennai',
    },
    vehicleType: 'Mobile Rescue Van (Equipped with Tools & Compressor)',
    completedJobs: 418,
    todayEarnings: 2450,
    totalEarnings: 184500,
    documents: {
      licenseNumber: 'TN07-2015-0045192',
      mechanicCert: 'Govt ITI Automobile Mechanic Cert #9812',
      verifiedAt: '2024-01-15',
    },
  },
  {
    id: 'prov-2',
    name: 'Sundar Rajan',
    businessName: 'Chennai Express Flatbed & Towing',
    phone: '+91 98410 77334',
    email: 'express.towing@yahoo.com',
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 289,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['towing', 'accident', 'breakdown'],
    serviceArea: 'Chennai City & ECR/OMR Highways',
    currentLocation: {
      lat: 12.918,
      lng: 80.222,
      address: 'Perumbakkam Main Road, Medavakkam',
    },
    vehicleType: 'Tata 1109 Hydraulic Flatbed Tow Truck',
    completedJobs: 375,
    todayEarnings: 4200,
    totalEarnings: 298000,
    documents: {
      licenseNumber: 'TN09-2012-0091823',
      mechanicCert: 'Heavy Commercial Vehicle & Rigging Cert #4412',
      verifiedAt: '2024-01-18',
    },
  },
  {
    id: 'prov-3',
    name: 'Balaji Natarajan',
    businessName: 'Balaji 24/7 Battery Jump & Electrical',
    phone: '+91 98402 33445',
    email: 'balaji.battery@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 512,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['battery', 'electrical', 'breakdown'],
    serviceArea: 'Adyar, Velachery, Guindy, Thiruvanmiyur',
    currentLocation: {
      lat: 12.951,
      lng: 80.241,
      address: 'SRP Tools Junction, OMR, Perungudi',
    },
    vehicleType: 'Rescue Two-Wheeler with Dual Jumpstart Booster & Alternator Tester',
    completedJobs: 620,
    todayEarnings: 1800,
    totalEarnings: 215000,
    documents: {
      licenseNumber: 'TN01-2016-0012984',
      mechanicCert: 'Exide & Amaron Certified Battery Technician',
      verifiedAt: '2024-02-01',
    },
  },
  {
    id: 'prov-4',
    name: 'Selvam Anthony',
    businessName: 'Selvam Rapid Tyre Care & Nitrogen Puncture',
    phone: '+91 98840 99881',
    email: 'selvamtyres@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 198,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['tyre', 'breakdown'],
    serviceArea: 'Navalur, Siruseri IT Park, Kelambakkam',
    currentLocation: {
      lat: 12.871,
      lng: 80.228,
      address: 'Opp. SIPCOT IT Park Main Gate, Siruseri',
    },
    vehicleType: 'Maruti Omni Mobile Puncture Unit with 10-bar Air Compressor',
    completedJobs: 245,
    todayEarnings: 1200,
    totalEarnings: 94000,
    documents: {
      licenseNumber: 'TN19-2018-0056123',
      mechanicCert: 'MRF Master Tyre Tech Certification',
      verifiedAt: '2024-02-10',
    },
  },
  {
    id: 'prov-5',
    name: 'Dinesh Kumar',
    businessName: 'SpeedResQ 24/7 Mechanical & Engine Assist',
    phone: '+91 94441 55667',
    email: 'dinesh.speedresq@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 165,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['mechanical', 'engine', 'breakdown', 'fuel'],
    serviceArea: 'Tambaram, Chromepet, Pallavaram, Medavakkam',
    currentLocation: {
      lat: 12.929,
      lng: 80.219,
      address: 'Medavakkam Koot Road Junction',
    },
    vehicleType: 'Mahindra Bolero Maxi Truck with Heavy Tool Chest & Jack System',
    completedJobs: 210,
    todayEarnings: 3100,
    totalEarnings: 152000,
    documents: {
      licenseNumber: 'TN11-2014-0078231',
      mechanicCert: 'Diploma in Mechanical Engineering (Automotive)',
      verifiedAt: '2024-02-22',
    },
  },
  {
    id: 'prov-6',
    name: 'Vigneshwaran R',
    businessName: 'Royal Riders Bike Doctor & Roadside Care',
    phone: '+91 99620 44551',
    email: 'vignesh.bikedoctor@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 410,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['tyre', 'fuel', 'breakdown', 'mechanical'],
    serviceArea: 'ECR, Kovalam, Mahabalipuram, Sholinganallur',
    currentLocation: {
      lat: 12.898,
      lng: 80.245,
      address: 'ECR Toll Plaza, Uthandi',
    },
    vehicleType: 'Modified Royal Enfield Himalayan with Tow Hitch & Spares Kit',
    completedJobs: 490,
    todayEarnings: 2100,
    totalEarnings: 176000,
    documents: {
      licenseNumber: 'TN07-2017-0034981',
      mechanicCert: 'Two Wheeler Master Technician Certified',
      verifiedAt: '2024-03-01',
    },
  },
  {
    id: 'prov-7',
    name: 'Anand Chandrasekar',
    businessName: 'Apex EV Mobile Support & Quick Charging',
    phone: '+91 98400 11998',
    email: 'anand.apexev@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 88,
    workStatus: 'OFFLINE',
    verificationStatus: 'PENDING',
    serviceCategories: ['battery', 'electrical', 'towing'],
    serviceArea: 'Guindy, T. Nagar, Nandanam, Saidapet',
    currentLocation: {
      lat: 13.006,
      lng: 80.208,
      address: 'Kathipara Urban Square, Guindy',
    },
    vehicleType: 'Tata Ace EV Mobile Charging Van with 15kW DC Fast Charger',
    completedJobs: 92,
    todayEarnings: 0,
    totalEarnings: 68000,
    documents: {
      licenseNumber: 'TN09-2020-0089234',
      mechanicCert: 'High Voltage EV Safety & Battery Servicing Cert (Arai)',
      verifiedAt: undefined,
    },
  },
  {
    id: 'prov-8',
    name: 'Mansoor Ali Khan',
    businessName: 'Highway Guardian Highway Patrol & Towing',
    phone: '+91 98418 22110',
    email: 'highway.guardian@rediffmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 142,
    workStatus: 'ONLINE',
    verificationStatus: 'VERIFIED',
    serviceCategories: ['towing', 'accident', 'mechanical'],
    serviceArea: 'GST Road, Vandalur, Tambaram, Chengalpattu Highway',
    currentLocation: {
      lat: 12.875,
      lng: 80.082,
      address: 'Near Vandalur Zoo Flyover, GST Road',
    },
    vehicleType: 'Ashok Leyland Heavy Under-lift & Crane Towing Vehicle',
    completedJobs: 175,
    todayEarnings: 5500,
    totalEarnings: 240000,
    documents: {
      licenseNumber: 'TN22-2011-0023419',
      mechanicCert: 'National Highway Rescue Incident Manager Cert',
      verifiedAt: '2024-01-05',
    },
  },
];

export const INITIAL_SAFE_PLACES: SafePlace[] = [
  {
    id: 'sp-1',
    name: 'Indian Oil Swagat 24/7 Fuel Hub & Rest Stop',
    type: 'fuel_station',
    distanceKm: 1.4,
    etaMinutes: 4,
    address: 'Survey 142, Rajiv Gandhi Salai (OMR), Sholinganallur, Chennai',
    lat: 12.905,
    lng: 80.228,
    phone: '+91 44 2450 1200',
    isOpen24x7: true,
    extraInfo: 'Clean restrooms, EV fast charger (60kW), ATM, 24-hour convenience store',
  },
  {
    id: 'sp-2',
    name: 'Bharat Petroleum Speed Point & Nitrogen Air',
    type: 'fuel_station',
    distanceKm: 2.8,
    etaMinutes: 7,
    address: 'Kandanchavadi Signal, OMR, Perungudi, Chennai',
    lat: 12.964,
    lng: 80.245,
    phone: '+91 44 2496 5501',
    isOpen24x7: true,
    extraInfo: 'Speed Petrol/Diesel, automatic air filling, mechanic bay on-site',
  },
  {
    id: 'sp-3',
    name: 'Apollo Speciality Hospital 24/7 Trauma & Emergency',
    type: 'hospital',
    distanceKm: 2.1,
    etaMinutes: 6,
    address: '05/639, Old Mahabalipuram Road, Thoraipakkam, Chennai',
    lat: 12.938,
    lng: 80.233,
    phone: '1066 / +91 44 2496 1111',
    isOpen24x7: true,
    extraInfo: 'Level-1 Emergency Trauma Care, 24x7 Ambulance dispatch, ICU on standby',
  },
  {
    id: 'sp-4',
    name: 'Gleneagles Global Health City Emergency Unit',
    type: 'hospital',
    distanceKm: 3.5,
    etaMinutes: 9,
    address: 'Cheran Nagar, Perumbakkam, Chennai',
    lat: 12.901,
    lng: 80.198,
    phone: '108 / +91 44 4477 7000',
    isOpen24x7: true,
    extraInfo: 'Advanced cardiac & roadside accident trauma facility with helipad',
  },
  {
    id: 'sp-5',
    name: 'J9 Thoraipakkam Traffic & Law Police Station',
    type: 'police',
    distanceKm: 1.8,
    etaMinutes: 5,
    address: 'Rajiv Gandhi Salai, Okkiyam Thoraipakkam, Chennai',
    lat: 12.928,
    lng: 80.232,
    phone: '112 / +91 44 2345 2812',
    isOpen24x7: true,
    extraInfo: 'Highway patrol dispatch, 24x7 desk, women safety helpline booth',
  },
  {
    id: 'sp-6',
    name: 'Bosch Multi-Brand 24/7 Quick Service Workshop',
    type: 'workshop',
    distanceKm: 3.2,
    etaMinutes: 8,
    address: 'Velachery-Tambaram Main Road, Pallikaranai, Chennai',
    lat: 12.935,
    lng: 80.209,
    phone: '+91 98400 44321',
    isOpen24x7: true,
    extraInfo: 'Computerized OBD diagnostics, hydraulic lifts, genuine spares warehouse',
  },
];

export const INITIAL_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'ec-1',
    name: 'Suresh Kumar (Brother)',
    phone: '+91 98401 99882',
    relationship: 'Brother',
  },
  {
    id: 'ec-2',
    name: 'Dr. Kavitha (Family Doctor)',
    phone: '+91 94440 12390',
    relationship: 'Doctor',
  },
  {
    id: 'ec-3',
    name: 'Deepa Kumar (Spouse)',
    phone: '+91 98410 44550',
    relationship: 'Spouse',
  },
];

export const INITIAL_REQUESTS: AssistanceRequest[] = [
  {
    id: 'RESQ-9041',
    customerId: 'cust-1',
    customerName: 'Ramesh Kumar',
    customerPhone: '+91 98401 23456',
    vehicle: INITIAL_VEHICLES[0],
    issueCategory: 'tyre',
    problemDescription: 'Rear right tyre hit debris on OMR near TCS Siruseri, sudden pressure drop and completely flat.',
    urgency: 'NORMAL',
    location: {
      lat: 12.9249,
      lng: 80.2272,
      address: 'OMR Road near Sholinganallur Junction, Chennai',
    },
    providerId: 'prov-1',
    providerName: 'Murugan Selvam (Murugan QuickFix)',
    providerPhone: '+91 98409 55112',
    providerRating: 4.9,
    providerLocation: {
      lat: 12.928,
      lng: 80.229,
      address: 'En route on OMR Service Road',
    },
    status: 'PROVIDER_ON_THE_WAY',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-18T14:10:00Z', note: 'Customer initiated assistance request via ResQ AI' },
      { status: 'SEARCHING', timestamp: '2024-04-18T14:10:30Z', note: 'Searching for nearest available tyre technician' },
      { status: 'PROVIDER_ASSIGNED', timestamp: '2024-04-18T14:11:15Z', note: 'Murugan QuickFix accepted the dispatch' },
      { status: 'PROVIDER_ON_THE_WAY', timestamp: '2024-04-18T14:12:00Z', note: 'Technician left shop with equipment (ETA 8 mins)' },
    ],
    serviceType: 'Flat Tyre / Puncture Repair',
    basePrice: 350,
    distanceKm: 2.1,
    totalPrice: 450,
    etaMinutes: 7,
    paymentStatus: 'pending',
    paymentMethod: 'upi',
    aiDiagnostic: {
      confidence: 94,
      observation: 'Tubeless tyre puncture or valve leakage on rear axle.',
      safetyAdvice: 'Park on highway shoulder, switch hazard flashers on, do not attempt to change tyre on active traffic side.',
    },
    createdAt: '2024-04-18T14:10:00Z',
    updatedAt: '2024-04-18T14:12:00Z',
  },
  {
    id: 'RESQ-8820',
    customerId: 'cust-2',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 98412 87654',
    vehicle: INITIAL_VEHICLES[2],
    issueCategory: 'battery',
    problemDescription: 'Car auxiliary 12V battery discharged after sitting with hazards on, electric drivetrain will not initialize.',
    urgency: 'URGENT',
    location: {
      lat: 12.964,
      lng: 80.245,
      address: 'Near Kandanchavadi Bus Stop, OMR, Chennai',
    },
    providerId: 'prov-3',
    providerName: 'Balaji Natarajan (Balaji 24/7 Battery)',
    providerPhone: '+91 98402 33445',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-16T10:15:00Z', note: 'Assistance request logged' },
      { status: 'PROVIDER_ASSIGNED', timestamp: '2024-04-16T10:17:00Z', note: 'Balaji assigned' },
      { status: 'PROVIDER_ON_THE_WAY', timestamp: '2024-04-16T10:19:00Z', note: 'Provider en route' },
      { status: 'ARRIVED', timestamp: '2024-04-16T10:29:00Z', note: 'Provider arrived at site' },
      { status: 'ASSISTANCE_IN_PROGRESS', timestamp: '2024-04-16T10:32:00Z', note: '12V auxiliary booster attached' },
      { status: 'COMPLETED', timestamp: '2024-04-16T10:48:00Z', note: 'Nexon EV powered up successfully, test driven' },
    ],
    serviceType: 'Battery Jumpstart & Health Check',
    basePrice: 500,
    distanceKm: 3.4,
    totalPrice: 650,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    review: 'Balaji arrived within 12 minutes! Very knowledgeable about EV 12V auxiliary batteries. Got my Nexon started immediately.',
    createdAt: '2024-04-16T10:15:00Z',
    updatedAt: '2024-04-16T10:48:00Z',
  },
  {
    id: 'RESQ-8712',
    customerId: 'cust-3',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 99520 11223',
    vehicle: INITIAL_VEHICLES[4],
    issueCategory: 'fuel',
    problemDescription: 'Fuel low indicator blinked for 15km, car stalled before reaching next fuel pump on bypass.',
    urgency: 'NORMAL',
    location: {
      lat: 12.912,
      lng: 80.218,
      address: 'Perumbakkam Main Road near Medavakkam flyover',
    },
    providerId: 'prov-2',
    providerName: 'Sundar Rajan (Chennai Express Towing)',
    providerPhone: '+91 98410 77334',
    providerRating: 4.8,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-15T18:00:00Z', note: 'Assistance logged' },
      { status: 'PROVIDER_ASSIGNED', timestamp: '2024-04-15T18:04:00Z', note: 'Tow service dispatched' },
      { status: 'COMPLETED', timestamp: '2024-04-15T18:50:00Z', note: 'Vehicle safely transported 2km to Indian Oil Petrol Station' },
    ],
    serviceType: 'Safe Towing to Nearest Fuel Station',
    basePrice: 1200,
    distanceKm: 2.8,
    totalPrice: 1450,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'card',
    rating: 5,
    review: 'Strictly followed legal safety standards, towed my car safely to the fuel pump. Excellent professionalism.',
    createdAt: '2024-04-15T18:00:00Z',
    updatedAt: '2024-04-15T18:50:00Z',
  },
  {
    id: 'RESQ-8650',
    customerId: 'cust-4',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 97890 44556',
    vehicle: INITIAL_VEHICLES[6],
    issueCategory: 'mechanical',
    problemDescription: 'Clutch pedal became completely loose while waiting at traffic signal, cannot engage 1st gear.',
    urgency: 'URGENT',
    location: {
      lat: 12.942,
      lng: 80.239,
      address: 'Near Thoraipakkam Toll Plaza, OMR, Chennai',
    },
    providerId: 'prov-5',
    providerName: 'Dinesh Kumar (SpeedResQ Mechanical)',
    providerPhone: '+91 94441 55667',
    providerRating: 4.8,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-14T08:30:00Z', note: 'Customer requested mechanical help' },
      { status: 'COMPLETED', timestamp: '2024-04-14T09:40:00Z', note: 'Clutch slave cylinder leak diagnosed, bleed done, safely reached workshop' },
    ],
    serviceType: 'Hydraulic Clutch Troubleshooting',
    basePrice: 600,
    distanceKm: 4.2,
    totalPrice: 850,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'cash',
    rating: 4,
    review: 'Mechanic Dinesh knew exactly how to bleed the Thar clutch system on roadside so I could shift safely.',
    createdAt: '2024-04-14T08:30:00Z',
    updatedAt: '2024-04-14T09:40:00Z',
  },
  {
    id: 'RESQ-8599',
    customerId: 'cust-5',
    customerName: 'Karthik Venkat',
    customerPhone: '+91 94440 66778',
    vehicle: INITIAL_VEHICLES[8],
    issueCategory: 'engine',
    problemDescription: 'Engine temperature indicator glowing bright red, steam escaping from radiator cap area.',
    urgency: 'URGENT',
    location: {
      lat: 12.951,
      lng: 80.241,
      address: 'OMR Road near SRP Tools, Perungudi, Chennai',
    },
    providerId: 'prov-2',
    providerName: 'Sundar Rajan (Chennai Express Towing)',
    providerPhone: '+91 98410 77334',
    providerRating: 4.8,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-12T16:20:00Z', note: 'Engine overheating reported' },
      { status: 'COMPLETED', timestamp: '2024-04-12T17:35:00Z', note: 'Flatbed towed to Kia Authorized Service Center' },
    ],
    serviceType: 'Flatbed Towing to Authorized Service Center',
    basePrice: 1500,
    distanceKm: 6.5,
    totalPrice: 1950,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    review: 'Flatbed truck handled the car very gently. Prevented catastrophic engine seizure.',
    createdAt: '2024-04-12T16:20:00Z',
    updatedAt: '2024-04-12T17:35:00Z',
  },
  {
    id: 'RESQ-8501',
    customerId: 'cust-1',
    customerName: 'Ramesh Kumar',
    customerPhone: '+91 98401 23456',
    vehicle: INITIAL_VEHICLES[1],
    issueCategory: 'breakdown',
    problemDescription: 'En Royal Enfield bike start aagala, self motor clicking sound mattum varuthu.',
    urgency: 'NORMAL',
    location: {
      lat: 12.898,
      lng: 80.245,
      address: 'ECR Toll Plaza, Uthandi, Chennai',
    },
    providerId: 'prov-6',
    providerName: 'Vigneshwaran R (Royal Riders Bike Doctor)',
    providerPhone: '+91 99620 44551',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-10T11:00:00Z', note: 'Bike breakdown requested in Tanglish' },
      { status: 'COMPLETED', timestamp: '2024-04-10T11:45:00Z', note: 'Starter relay replaced on spot, bike test started' },
    ],
    serviceType: 'Two Wheeler On-Spot Relay & Electrical Fix',
    basePrice: 400,
    distanceKm: 1.5,
    totalPrice: 550,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    review: 'Bike doctor Vignesh came on his Himalayan with the exact Royal Enfield starter relay! Fantastic service.',
    createdAt: '2024-04-10T11:00:00Z',
    updatedAt: '2024-04-10T11:45:00Z',
  },
  {
    id: 'RESQ-8452',
    customerId: 'cust-2',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 98412 87654',
    vehicle: INITIAL_VEHICLES[3],
    issueCategory: 'tyre',
    problemDescription: 'Activa front tyre puncture near shopping complex.',
    urgency: 'NORMAL',
    location: {
      lat: 12.9352,
      lng: 80.2315,
      address: 'Sholinganallur Junction, Chennai',
    },
    providerId: 'prov-4',
    providerName: 'Selvam Anthony (Selvam Rapid Tyre)',
    providerPhone: '+91 98840 99881',
    providerRating: 4.7,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-08T15:10:00Z', note: 'Puncture repair logged' },
      { status: 'COMPLETED', timestamp: '2024-04-08T15:35:00Z', note: 'Mushroom patch tubeless puncture fixed' },
    ],
    serviceType: 'Scooter Tubeless Puncture Service',
    basePrice: 200,
    distanceKm: 1.2,
    totalPrice: 250,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'cash',
    rating: 5,
    createdAt: '2024-04-08T15:10:00Z',
    updatedAt: '2024-04-08T15:35:00Z',
  },
  {
    id: 'RESQ-8390',
    customerId: 'cust-3',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 99520 11223',
    vehicle: INITIAL_VEHICLES[4],
    issueCategory: 'accident',
    problemDescription: 'Minor collision at roundabout, bumper dislodged and rubbing front left tyre, vehicle cannot be driven safely.',
    urgency: 'URGENT',
    location: {
      lat: 12.929,
      lng: 80.219,
      address: 'Medavakkam Junction, Chennai',
    },
    providerId: 'prov-2',
    providerName: 'Sundar Rajan (Chennai Express Towing)',
    providerPhone: '+91 98410 77334',
    providerRating: 4.8,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-05T19:00:00Z', note: 'Incident logged' },
      { status: 'COMPLETED', timestamp: '2024-04-05T20:10:00Z', note: 'Towed to Maruti Authorized Body Shop' },
    ],
    serviceType: 'Accident Recovery & Towing',
    basePrice: 1500,
    distanceKm: 3.5,
    totalPrice: 1850,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'card',
    rating: 4,
    createdAt: '2024-04-05T19:00:00Z',
    updatedAt: '2024-04-05T20:10:00Z',
  },
  {
    id: 'RESQ-8310',
    customerId: 'cust-4',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 97890 44556',
    vehicle: INITIAL_VEHICLES[7],
    issueCategory: 'electrical',
    problemDescription: 'Headlight and instrument cluster went black on dark road.',
    urgency: 'URGENT',
    location: {
      lat: 12.871,
      lng: 80.228,
      address: 'Near Siruseri Sipcot Gate, Chennai',
    },
    providerId: 'prov-6',
    providerName: 'Vigneshwaran R (Royal Riders Bike Doctor)',
    providerPhone: '+91 99620 44551',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-04-02T21:10:00Z', note: 'Night electrical failure logged' },
      { status: 'COMPLETED', timestamp: '2024-04-02T21:40:00Z', note: 'Main 20A fuse replaced and short wire taped' },
    ],
    serviceType: 'Emergency Night Electrical Inspection',
    basePrice: 450,
    distanceKm: 2.0,
    totalPrice: 550,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    createdAt: '2024-04-02T21:10:00Z',
    updatedAt: '2024-04-02T21:40:00Z',
  },
  {
    id: 'RESQ-8255',
    customerId: 'cust-5',
    customerName: 'Karthik Venkat',
    customerPhone: '+91 94440 66778',
    vehicle: INITIAL_VEHICLES[9],
    issueCategory: 'breakdown',
    problemDescription: 'Small commercial truck differential noise and speed dropped.',
    urgency: 'NORMAL',
    location: {
      lat: 12.875,
      lng: 80.082,
      address: 'GST Road, Vandalur, Chennai',
    },
    providerId: 'prov-8',
    providerName: 'Mansoor Ali Khan (Highway Guardian)',
    providerPhone: '+91 98418 22110',
    providerRating: 4.6,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-29T12:00:00Z', note: 'Commercial vehicle breakdown logged' },
      { status: 'COMPLETED', timestamp: '2024-03-29T13:30:00Z', note: 'Towed to Tata Motors Commercial Bay' },
    ],
    serviceType: 'Commercial Light Truck Towing',
    basePrice: 1800,
    distanceKm: 8.0,
    totalPrice: 2400,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 4,
    createdAt: '2024-03-29T12:00:00Z',
    updatedAt: '2024-03-29T13:30:00Z',
  },
  {
    id: 'RESQ-8190',
    customerId: 'cust-1',
    customerName: 'Ramesh Kumar',
    customerPhone: '+91 98401 23456',
    vehicle: INITIAL_VEHICLES[0],
    issueCategory: 'battery',
    problemDescription: 'Parked in office basement with cabin light left on over weekend.',
    urgency: 'NORMAL',
    location: {
      lat: 12.9249,
      lng: 80.2272,
      address: 'Ascendas IT Park Basement Parking, Taramani',
    },
    providerId: 'prov-3',
    providerName: 'Balaji Natarajan (Balaji 24/7 Battery)',
    providerPhone: '+91 98402 33445',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-25T09:15:00Z', note: 'Basement jumpstart requested' },
      { status: 'COMPLETED', timestamp: '2024-03-25T09:40:00Z', note: 'Portable booster pack jumpstart completed' },
    ],
    serviceType: 'Basement Portable Jumpstart',
    basePrice: 450,
    distanceKm: 1.8,
    totalPrice: 550,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    review: 'Great service! Technician brought portable jump pack since vehicle was parked tight against the basement wall.',
    createdAt: '2024-03-25T09:15:00Z',
    updatedAt: '2024-03-25T09:40:00Z',
  },
  {
    id: 'RESQ-8111',
    customerId: 'cust-2',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 98412 87654',
    vehicle: INITIAL_VEHICLES[2],
    issueCategory: 'tyre',
    problemDescription: 'Tyre valve stem cracked, slow air leak.',
    urgency: 'LOW',
    location: {
      lat: 12.938,
      lng: 80.233,
      address: 'Thoraipakkam, OMR, Chennai',
    },
    providerId: 'prov-1',
    providerName: 'Murugan Selvam (Murugan QuickFix)',
    providerPhone: '+91 98409 55112',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-20T17:00:00Z', note: 'Valve replacement requested' },
      { status: 'COMPLETED', timestamp: '2024-03-20T17:30:00Z', note: 'New metallic brass valve installed' },
    ],
    serviceType: 'Valve Stem Replacement & Nitrogen Refill',
    basePrice: 300,
    distanceKm: 1.5,
    totalPrice: 400,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'cash',
    rating: 5,
    createdAt: '2024-03-20T17:00:00Z',
    updatedAt: '2024-03-20T17:30:00Z',
  },
  {
    id: 'RESQ-8042',
    customerId: 'cust-3',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 99520 11223',
    vehicle: INITIAL_VEHICLES[5],
    issueCategory: 'battery',
    problemDescription: 'Electric scooter display showed error code 44, motor cut off.',
    urgency: 'NORMAL',
    location: {
      lat: 12.951,
      lng: 80.241,
      address: 'Perungudi Toll, Chennai',
    },
    providerId: 'prov-6',
    providerName: 'Vigneshwaran R (Royal Riders Bike Doctor)',
    providerPhone: '+91 99620 44551',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-15T14:00:00Z', note: 'EV bike error reported' },
      { status: 'COMPLETED', timestamp: '2024-03-15T14:40:00Z', note: 'BMS reset procedure executed successfully' },
    ],
    serviceType: 'EV Two-Wheeler BMS Diagnostics & Reset',
    basePrice: 500,
    distanceKm: 2.2,
    totalPrice: 650,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    createdAt: '2024-03-15T14:00:00Z',
    updatedAt: '2024-03-15T14:40:00Z',
  },
  {
    id: 'RESQ-7998',
    customerId: 'cust-4',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 97890 44556',
    vehicle: INITIAL_VEHICLES[6],
    issueCategory: 'fuel',
    problemDescription: 'Fuel tank gauge sender failed, unexpectedly ran dry on bypass.',
    urgency: 'NORMAL',
    location: {
      lat: 12.905,
      lng: 80.228,
      address: 'Indian Oil Swagat Fuel Hub, Sholinganallur',
    },
    providerId: 'prov-1',
    providerName: 'Murugan Selvam (Murugan QuickFix)',
    providerPhone: '+91 98409 55112',
    providerRating: 4.9,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-10T11:20:00Z', note: 'Fuel guidance request' },
      { status: 'COMPLETED', timestamp: '2024-03-10T12:00:00Z', note: 'Safely escorted 800m to authorized fuel dispenser' },
    ],
    serviceType: 'Roadside Escort to Authorized Fuel Station',
    basePrice: 400,
    distanceKm: 0.8,
    totalPrice: 450,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'upi',
    rating: 5,
    createdAt: '2024-03-10T11:20:00Z',
    updatedAt: '2024-03-10T12:00:00Z',
  },
  {
    id: 'RESQ-7920',
    customerId: 'cust-5',
    customerName: 'Karthik Venkat',
    customerPhone: '+91 94440 66778',
    vehicle: INITIAL_VEHICLES[8],
    issueCategory: 'mechanical',
    problemDescription: 'Serpentine accessory belt snapped, battery charge warning light and power steering failure.',
    urgency: 'URGENT',
    location: {
      lat: 12.918,
      lng: 80.222,
      address: 'Medavakkam Main Road, Chennai',
    },
    providerId: 'prov-5',
    providerName: 'Dinesh Kumar (SpeedResQ Mechanical)',
    providerPhone: '+91 94441 55667',
    providerRating: 4.8,
    status: 'COMPLETED',
    timeline: [
      { status: 'REQUESTED', timestamp: '2024-03-05T16:15:00Z', note: 'Accessory drive belt snapped' },
      { status: 'COMPLETED', timestamp: '2024-03-05T17:30:00Z', note: 'New drive belt tensioned and fitted on roadside' },
    ],
    serviceType: 'Accessory Drive Belt Replacement',
    basePrice: 850,
    distanceKm: 3.1,
    totalPrice: 1100,
    etaMinutes: 0,
    paymentStatus: 'completed',
    paymentMethod: 'card',
    rating: 5,
    createdAt: '2024-03-05T16:15:00Z',
    updatedAt: '2024-03-05T17:30:00Z',
  },
];
